comment: false

coverage:
  status:
    project:
      default:
        threshold: 2%

github_checks:
  annotations: false

ignore:
  - 'contracts/' # Disabled due to solidity-coverage not reporting coverage
  - 'core/internal'
  - 'core/scripts'
